services:
  - type: web
    name: app-100
    env: node
    region: oregon
    plan: free
    branch: master
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_VERSION
        value: 22.13.0
      - key: PNPM_VERSION
        value: 9.12.0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
